Bienvenue dans Orgzly!

* Notes
** Cliquez sur la note pour l’ouvrir
** Cliquez et restez appuyé·e sur la note pour la sélectionner

Vous pouvez sélectionner plusieurs notes.

** Appuyez et glissez rapidement une note vers la droite pour ouvrir son menu rapide

** Appuyez et glissez rapidement vers la gauche pour ouvrir un autre menu.

** Dépliez une note qui contient des sous-notes en cliquant sur l'icône à droite

Appuyez longuement pour ouvrir toute la sous-arborescence.

*** Il n’y a pas de limite au nombre de niveaux que vous pouvez avoir
**** Utilisez ceci pour mieux organiser vos notes

** Les notes peuvent avoir des étiquettes :tag1:tag2:
*** Les sous-notes héritent des étiquettes parentes :tag3:

Si vous recherchez des notes avec le tag “tag1” en utilisant la requête “t.tag1”, cette note sera incluse dans les résultats de recherche.

*** Une note qui a la balise =ARCHIVE= est grisée :ARCHIVE:

** TODO Les notes peuvent avoir un état

Vous pouvez configurer tous les états que vous souhaitez : TODO, NEXT, DONE, etc.

*** Il y a deux /types/ d'état : à faire et terminé

*** DONE C'est une note avec un type d'état /fait/
CLOSED: [2018-01-24 Mer 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** L'horaire peut avoir un répetiteur
SCHEDULED: <2015-02-16 Mon .+2d>

** Vous pouvez également définir une échéance
DEADLINE: <2015-02-20 Fri>

** Les rappels pour les dates planifiées ou d'échéances sont supportés

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

Vous pouvez modifier le nombre de priorités dans les paramètres. Vous pouvez également changer la priorité par défaut - la priorité assumée lorsqu'elle n'est pas définie.

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** Les formatages de base sont supportés

Vous pouvez mettre les mots en *gras*, /italique/, _souligné_, =verbatim=, ~en code~ ou les +biffer+.

** Les liste de cases à cocher sont utilsables

** [#A] Note can have a priority

- [X] Tâche 1
- [X] Tâche 2
- [X] Tâche 3

Un appui sur la case à cocher change son état. Un retour à la ligne crée une nouvelle case à cocher.

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
