Wilkommen bei Orgzly!

* Notizen
** Klicken Sie auf die Notiz, um sie zu öffnen
** Klicken und halten Sie die Notiz, um sie auszuwählen

Sie können mehrere Notizen auswählen.

** Notiz nach rechts wischen, um deren Schnellmenü zu öffnen

Notiz nach links wischen, um ein anderes Menü zu öffnen.

** Unterpunkte einer Notiz können Sie einklappen, indem Sie das Symbol neben ihr antippen

Halten Sie das Symbol gedrückt, um den gesamten Unterbaum aufzuklappen.

*** Es existiert keine Begrenzung bei der möglichen Anzahl der Ebenen
**** Dies hilft dabei, Ihre Notizen besser zu organisieren

** Notizen können Schlagwörter besitzen :Schlagwort1:Schlagwort2:
*** Unternotizen erben die Schlagwörter :tag3:

Wenn Sie mit der Abfrage „t.Schlagwort1“ nach Notizen mit dem Schlagwort „Schlagwort1“ suchen, wird diese Notiz in die Suchergebnisse aufgenommen.

*** Eine Notiz mit dem Schlagwort =ARCHIVE= ist ausgegraut :ARCHIVE:

** TODO-Notizen können einen Status besitzen

Sie können eine beliebige Anzahl zu verwendender Status konfigurieren: TODO, NEXT, DONE usw.

*** Es gibt zwei /Statusarten/: „to-do“ (zu erledigen) und „done“ (erledigt)

*** DONE Dies ist eine Notiz mit dem Status /done/ (also erledigt)
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** Es gibt eine Wiederholungsfunktion für Termine
SCHEDULED: <2015-02-16 Mon .+2d>

** Sie können auch eine Frist festlegen
DEADLINE: <2015-02-20 Fri>

** Erinnerungen für Termine und Fristen

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

Die verschiedenen Prioritätsstufen können in den Einstellungen verändert werden. Ebenso kann die Priorität angepasst werden, die Notizen ohne explizite Priorisierung zugeordnet wird.

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** Grundlegende typografische Hervorhebungen werden unterstützt

Sie können Wörter *fett*, /kursiv/, _unterstrichen_, =verbatim=, ~als Code~ und +durchgestrichen+ darstellen.

** Verwenden von Kontrollkästchen

** [#A] Note can have a priority

- [X] Aufgabe 1
- [ ] Aufgabe 2
- [ ] Aufgabe 3

Klicken Sie auf das Kontrollkästchen, um es zu wechseln. Wenn Sie aus einer Zeile mit Kontrollkästchen eine neue Zeile erstellen, wird diese Zeile ebenfalls ein Kontrollkästchen beinhalten.

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
