Witaj w Orgzly!

* Notatki
** Kliknij notatkę, aby ją otworzyć
** Kliknij i przytrzymaj notatkę, aby ją zaznaczyć

Możesz zaznaczyć wiele notatek.

** Przeciągnij notatkę w prawo, aby otworzyć szybkie menu

Przeciągnij w lewo, aby otworzyć inne menu.

** Zwiń notatkę, która zawiera inne notatki, klikając ikonę „–” obok niej

Przytrzymaj ikonę „+”, aby rozwinąć wszystkie podrzędne notatki.

*** Liczba poziomów notatek jest nieograniczona
**** Wykorzystaj to, aby lepiej uporządkować swoje notatki

** Notatka może mieć przypisane znaczniki :znacznik1:znacznik2:
*** Podrzędna notatka dziedziczy znaczniki :znacznik3:

Jeśli wyszukasz notatki ze znacznikiem „znacznik1” za pomocą zapytania „t.znacznik1”, to ta notatka zostanie uwzględniona w wynikach wyszukiwania.

*** A note that has the =ARCHIVE= tag set is grayed out :ARCHIVE:

** TODO Notatka może mieć przypisany stan

Możesz skonfigurować dowolną liczbę stanów do użycia: TODO, NEXT, DONE, itp.

*** Istnieją dwa /typy/ stanów: do zrobienia i zrobione

*** DONE To jest notatka ze /zrobionym/ typem stanu
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** Zaplanowane terminy mogą się okresowo powtarzać
SCHEDULED: <2015-02-16 Mon .+2d>

** Możesz również ustawić termin ostateczny
DEADLINE: <2015-02-20 Fri>

** Obsługiwane są przypomnienia o zaplanowanych i ostatecznych terminach

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

Możesz zmienić liczbę poziomów priorytetów w ustawieniach. Możesz również zmienić domyślny priorytet, przypisywany notatkom, które nie mają ustawionego żadnego.

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** Orgzly wspiera podstawowe formatowanie tekstu

Możesz stosować *pogrubienie*, /kursywę/, _podkreślenie_, =dosłowny tekst=, ~kod~ i +przekreślenie+.

** Możliwe jest tworzenie list do odhaczania

** [#A] Note can have a priority

- [X] Zadanie „1”
- [ ] Zadanie „2”
- [ ] Zadanie „3”

Kliknij pole wyboru, aby je przełączyć. Naciśnij klawisz ENTER na końcu linii, aby utworzyć nowy element listy.

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
