Bem-vindo ao Orgzly!

* Notas
** Clique em uma nota para abri-la
** Clique e segure em uma nota para selecioná-la

Você pode selecionar múltiplas notas.

** Deslize a nota para direita para abrir um menu rápido

Deslize para a esquerda para abrir um menu diferente.

** Oculte uma nota que contenha sub-notas clicando no ícone ao lado dela

Segure no ícone para expandir a sub-árvore inteira.

*** Não há um limite de níveis que você pode ter
**** Use isso para organizar melhor as suas anotações

** Notas podem ter tags :tag1:tag2:
*** Sub-notas herdam as tags :tag3:

Se você pesquisar por notas com a tag "tag1" usando a consulta "t.tag1", esta nota será incluída nos resultados da pesquisa.

*** Uma nota que contém a tag =ARCHIVE= fica acinzentada :ARCHIVE:

** TODO Notas podem ter um estado

Você pode configurar quantos estados quiser: TODO, NEXT, DONE, etc.

*** Existem dois /tipos/ de estados: a-fazer (todo) e concluído (done)

*** DONE Isto é uma nota com o tipo de estado concluído (done)
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** Horários podem ter um repetidor
SCHEDULED: <2015-02-16 Mon .+2d>

** Você também pode definir um prazo limite
DEADLINE: <2015-02-20 Fri>

** Lembretes para agendamento e horário do prazo limite são suportados

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

Você pode alterar o número de prioridades nas Configurações. Você também pode alterar a prioridade padrão - definindo prioridade para as notas que não possuem.

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** Ênfase tipográfica básica é suportada

Você pode deixar as palavras *negrito*, /itálico/, _sublinhado_, =textuais=, ~código~ e +riscado+.

** Checklists podem ser criados

** [#A] Note can have a priority

- [X] Tarefa 1
- [ ] Tarefa 2
- [ ] Tarefa 3

Clique na caixa de seleção para marcá-lo. Tecle enter no final da linha para criar um novo item.

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
