Välkommen till Orgzly!

* Anteckningar
** Klicka på en anteckning för att öppna den
** Långklicka på anteckningen för att markera den

Du kan markera flera anteckningar.

** Svep anteckningen åt höger för att öppna dess popup-meny

Svep anteckningen åt vänster för att öppna en annan meny.

** Du kan fälla ihop en anteckning som innehåller under-anteckningar genom att klicka på ikonen bredvid den

Långklicka på ikonen för att fälla ut hela underträdet.

*** Det finns ingen gräns för hur många nivåer du kan ha
**** Använd detta för att organisera dina anteckningar bättre

** En anteckning kan ha taggar :tag1:tag2:
*** Underordnade anteckningar ärver taggar ovanför :tag3:

Om du söker efter anteckningar taggade med “tag1” med hjälp av sökfrågan “t.tag1” så kommer denna anteckning att komma med i sökresultatet.

*** En anteckning med taggen =ARCHIVE= visas som utgråad :ARCHIVE:

** Anteckningar kan ha en status

Du kan själv konfigurera valfritt antal möjliga statusar: TODO, NEXT, DONE, osv.

*** TODO Det finns två /typer/ av status: ”to-do” och ”klar”

*** DONE Denna antecknings status är av typen /klar/
CLOSED: [2018-01-24 Wed 17:00]

** En antecknings rubrik kan visa status hos dess underordnade anteckningar [1/3] [33%]

*** TODO För att se kvoten mellan TODO- och DONE-statusar, lägg till [/] i rubriken

*** TODO För att visa relationen mellan TODO- och DONE-status i procent, lägg till [%] i rubriken

*** DONE Båda två kan användas samtidigt
CLOSED: [2025-03-13 Thu 08:37]

Ordningen har ingen betydelse, och siffrorna uppdateras automatiskt.

** Anteckningar kan schemaläggas till en viss tidpunkt
SCHEDULED: <2015-02-20 Fri 15:15>

*** Tidpunkter kan innehålla en repeterare
SCHEDULED: <2015-02-16 Mon .+2d>

** Du kan också sätta en deadline
DEADLINE: <2015-02-20 Fri>

** Händelsetider kan användas var som helst i anteckningens innehåll

Det kan finnas flera händelsetider:

- <2015-02-20 Fri>
- <2015-02-21 Sat>

** Orgzly kan visa påminnelser om anteckningar som är schemalagda, har en deadline, eller innehåller en händelsetid

Klarmarkera anteckningen för att flytta fram repeteraren.

** [#A] Anteckningar kan ha en prioritet

Du kan ändra antalet möjliga prioritetsnivåer i Inställningar. Du kan också ändra standardprioriteten – den prioritet som anteckningar antas ha när ingen har angetts.

** Anteckningar kan innehålla länkar

Ring ett telefonnummer (tel:555-0199), skicka ett SMS (sms:555-0199), skriv ett mail (mailto:support@orgzlyrevived.com) eller besök en webbplats ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

Du kan också länka till en annan anteckning eller anteckningsbok i appen.

Besök [[https://www.orgzlyrevived.com/docs#links]] för mer information.

** Orgzly stöder grundläggande typografisk formatering

Text kan visas som *fetstilt*, /kursiv/, _understruken_, =ordagrann=, ~kod~ och +överstruken+.

** Du kan skapa och uppdatera checklistor

- [X] Uppgift 1
- [ ] Uppgift 2
- [ ] Uppgift 3

Klicka i rutan för att klarmarkera den. Tryck på Enter vid slutet av den sista raden för att lägga till en post i listan.

** En antecknings rubrik kan också visa status hos checklistor [66%] [2/3]

- [X] Uppgift 1
- [ ] Uppgift 2
- [X] Uppgift 3

* Söka
** Orgzly stöder många olika sökoperatorer

Du kan söka efter anteckningar baserat på status, taggar, schemalagd tid, deadline, händelsetider, med mera.

Besök [[https://www.orgzlyrevived.com/docs#search]] för att få veta mer.

** Sökfrågor kan sparas för snabb åtkomst

Testa de förinställda sökfrågorna i navigeringslådan och lägg märke till deras syntax.

Du kan skapa egna sparade sökningar genom att klicka på ”Sökningar” i navigeringslådan.

* Synkronisera

** Anteckningsböcker kan sparas som vanliga textfiler

Textfilerna sparas i formatet som används av [[https://orgmode.org/][Org mode]].

** Olika typer av lagringsplatser

En lagringsplats är en plats dit du kan synka dina anteckningsböcker. Det kan vara en mapp på din mobila enhet eller SD-kort, en WebDAV-katalog, eller Dropbox.
