Orgzly へようこそ!

* メモ
** メモをクリックすると開きます
** メモをロングタップすると選択できます

複数のメモを選択できます。

** メモを右にスワイプすると、クイックメニューが開きます

左にスワイプすると、別のメニューが開きます。

** メモは階層を持つことができ、隣のアイコンをタップすると折りたためます

アイコンをロングタップすると配下の全てを広げます

*** 階層の数に上限はありません
**** これを使うと、メモをうまく整理できます

** メモはタグを付けられます :tag1:tag2:
*** 下の階層のメモは、親階層のタグを引き継ぎます :tag3:

"tag1"を検索する"t.tag1"クエリを使うと、このメモも検索結果に含まれます

*** =ARCHIVE= タグのついたメモはグレーアウト表示されます :ARCHIVE:

** TODO メモには状態を付けられます

状態はいくつでも設定できます。 TODO, NEXT, DONE, などです。

*** 状態には2つのタイプがあります。to-doとdoneです。

*** DONE これはdoneタイプの状態のメモです
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** TODO To track the percentage of DONE vs TODO items, add [%] to the note's title

*** DONE Both can be used in tandem
CLOSED: [2025-03-13 Thu 08:37]

The order doesn't matter, and the counts will be updated automatically.

** メモには予定日時をつけることができます
SCHEDULED: <2015-02-20 Fri 15:15>

*** 日時には繰り返しを指定できます
SCHEDULED: <2015-02-16 Mon .+2d>

** 期限日時も設定できます
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

- <2015-02-20 Fri>
- <2015-02-21 Sat>

** 予定と期限日時の通知をサポートしています

初期設定では無効になっているので、必要であれば設定から有効にしてください。

** [#A] メモには優先度を付けることができます

優先度の数は、設定から変更できます。 メモに優先度を指定しなかったときに仮定される、暗黙の優先度も変更できます。

** メモにはリンクを含めることができます

電話をかける (tel:555-0199), SMS送信 (sms:555-0199), メール編集 (mailto:support@orgzlyrevived.com) Webページを開く ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

アプリ内の、別のメモやメモ帳にも、リンクができます。

詳しくは https://www.orgzlyrevived.com/docs#links を見てください。

** 基本的なタイポグラフィをサポートします

こんな感じ *ボールド*, /イタリック/, _下線_, =逐語的=, ~コード~, +取り消し+.

** チェックボックスリストが利用できます

- [X] タスク1
- [ ] タスク2
- [ ] タスク3

チェックボックスをタップすると、トグルできます。 行末で改行すると、新しいアイテムが作れます。

** A note's title can also track checkbox list states [66%] [2/3]

- [X] タスク1 1
- [ ] タスク1 2
- [X] タスク1 3

* 検索
** 多くの検索演算子をサポートしています

状態、タグ、予定日時、期限日時などで、メモを検索できます。

詳しくは [[https://www.orgzlyrevived.com/docs#search]] を見てください。

** 検索クエリは、クイックアクセスに保存できます

ナビゲーションドロワーからサンプルの検索を試し、そのクエリに注目してください。

ナビゲーションドロワーの"検索"をタップして、あなた用の検索を作ることができます。

* 同期

** メモ帳はプレーンテキストとして保存できます

ファイルは [[https://orgmode.org/][Org mode]] フォーマットが使われます。

** 場所 (リポジトリ) の種類

メモ帳は、モバイル デバイス、SD カード、Dropbox 上のディレクトリと同期することができます。
