Orgzly へようこそ!

* メモ
** メモをクリックすると開きます
** メモをロングタップすると選択できます

複数のメモを選択できます。

** メモを右にスワイプすると、クイックメニューが開きます

左にスワイプすると、別のメニューが開きます。

** メモは階層を持つことができ、隣のアイコンをタップすると折りたためます

アイコンをロングタップすると配下の全てを広げます

*** 階層の数に上限はありません
**** これを使うと、メモをうまく整理できます

** メモはタグを付けられます :tag1:tag2:
*** 下の階層のメモは、親階層のタグを引き継ぎます :tag3:

"tag1"を検索する"t.tag1"クエリを使うと、このメモも検索結果に含まれます

*** =ARCHIVE= タグのついたメモはグレーアウト表示されます :ARCHIVE:

** TODO メモには状態を付けられます

状態はいくつでも設定できます。 TODO, NEXT, DONE, などです。

*** 状態には2つのタイプがあります。to-doとdoneです。

*** DONE これはdoneタイプの状態のメモです
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** 日時には繰り返しを指定できます
SCHEDULED: <2015-02-16 Mon .+2d>

** 期限日時も設定できます
DEADLINE: <2015-02-20 Fri>

** 予定と期限日時の通知をサポートしています

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

優先度の数は、設定から変更できます。 メモに優先度を指定しなかったときに仮定される、暗黙の優先度も変更できます。

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** 基本的なタイポグラフィをサポートします

こんな感じ *ボールド*, /イタリック/, _下線_, =逐語的=, ~コード~, +取り消し+.

** チェックボックスリストが利用できます

** [#A] Note can have a priority

- [X] タスク1
- [ ] タスク2
- [ ] タスク3

チェックボックスをタップすると、トグルできます。 行末で改行すると、新しいアイテムが作れます。

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
