Boas-vindas ao Orgzly!

* Notas
** Toque numa nota para abri-la
** Toque e segure a nota para seleciona-la

Você pode selecionar várias notas.

** Deslize a nota para a direita para abrir o menu rápido

Deslizar para a esquerda abre um menu diferente.

** Feche uma nota que contenha sub-notas clicando no ícone próxima a ela

Toque longo no ícone abre a subárvore inteira.

*** Não há limites na quantidade de níveis que você pode ter
**** Use isso para organizar suas notas de uma forma melhor

** Notas podem ter etiquetas :tag1:tag2:
*** Sub-notas herdam as etiquetas :tag3:

Se você pesquisar por notas com a etiqueta "tag1" usando a consulta "t.tag1", esta nota será incluida nos resultados da busca.

*** A note that has the =ARCHIVE= tag set is grayed out :ARCHIVE:

** TODO Notas podem ter um estado

Você pode configurar qualquer quantidade de estados para uso: TODO, NEXT, DONE etc.

Existem dois /tipos/ de estados: afazeres e feito

*** DONE isto é uma nota com o tipo de estado /feito/
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** Datas podem ter um repetidor
SCHEDULED: <2015-02-16 Mon .+2d>

** Você também pode definir uma data limite
DEADLINE: <2015-02-20 Fri>

** Lembretes para dias agendados e datas limite são suportados

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

Você pode alterar a quantidade de prioridades nas Configurações. Você também pode alterar a prioridade padrão - assumida por notas sem prioridades definidas explicitamente.

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** Ênfase tipográfica básica é suportada

Você pode escrever palavras em *negrito*, /itálico/, _sublinhado_, =citação=, ~monoespaçado~ e +tachado+.

** Caixas de seleção estão disponíveis

** [#A] Note can have a priority

- [X] Tarefa 1
- [ ] Tarefa 2
- [ ] Tarefa 3

Selecione a caixa de seleção para marcá-la / desmarcá-la. Pressione o botão de nova linha no fim da linha para criar um novo item.

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
