Ласкаво просимо до Orgzly!

* Нотатки
** Клацніть по нотатці, щоб відкрити її
** Клацніть по нотатці і утримуйте, щоб виділити її

Можна виділяти декілька нотаток.

** Потягніть нотатку вправо, щоб відкрити швидке меню

Потягніть нотатку вліво, щоб відкрити додаткове меню.

** Щоб згорнути нотатку з піднотатками, натисніть на значок поряд із нею

Довге натискання по значку розгортає весь вміст.

*** Нотатки можуть мати необмежену кількість рівнів
***** Використовуйте це, щоб краще організувати свої нотатки

** Нотатки можуть мати мітки :мітка1:мітка2:
*** Вкладені нотатки наслідують мітки :tag3:

Якщо Ви шукаєте нотатки з міткою «мітка1» за допомогою запиту «t.мітка1», то ця нотатка врахується до результатів пошуку.

*** Нотатка з міткою =ARCHIVE= виділяється сірим :ARCHIVE:

** TODO Нотатки можуть мати стан

Ви можете налаштувати будь-яку кількість станів та використовувати їх: TODO, NEXT, DONE і так далі.

*** Є два /типи/ станів: to-do і done

*** DONE Це нотатка з /виконаним/ типом стану
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** Час може повторюватися
SCHEDULED: <2015-02-16 Mon .+2d>

** Ви також можете встановити час завершення
DEADLINE: <2015-02-20 Fri>

** Підтримуються нагадування для нотаток із запланованим часом і кінцевим терміном

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

Ви можете змінити кількість пріоритетів у Налаштуваннях. Також Ви можете змінити стандартний пріоритет, який пропонується для нотаток, де його не встановлено.

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** Підтримуються основні типографічні виділення

Ви можете робити слова *грубими*, /похилими/, _підкресленими_, =без форматування=, ~кодом~ і +закресленими+.

** Доступний список із вимикачами

** [#A] Note can have a priority

- [X] Завдання 1
- [ ] Завдання 2
- [ ] Завдання 3

Натисніть на вимикач, щоб змінити стан. Натисніть кнопку нового рядка *⤶* в кінці рядка, щоб додати новий елемент.

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
