Ласкаво просимо до Orgzly!

* Нотатки
** Клацніть по нотатці, щоб відкрити її
** Клацніть по нотатці і утримуйте, щоб виділити її

Можна виділяти декілька нотаток.

** Потягніть нотатку вправо, щоб відкрити швидке меню

Потягніть нотатку вліво, щоб відкрити додаткове меню.

** Щоб згорнути нотатку з піднотатками, натисніть на значок поряд із нею

Довге натискання по значку розгортає весь вміст.

*** Нотатки можуть мати необмежену кількість рівнів
***** Використовуйте це, щоб краще організувати свої нотатки

** Нотатки можуть мати мітки :мітка1:мітка2:
*** Вкладені нотатки наслідують мітки :tag3:

Якщо Ви шукаєте нотатки з міткою «мітка1» за допомогою запиту «t.мітка1», то ця нотатка врахується до результатів пошуку.

*** Нотатка з міткою =ARCHIVE= виділяється сірим :ARCHIVE:

** TODO Нотатки можуть мати стан

Ви можете налаштувати будь-яку кількість станів та використовувати їх: TODO, NEXT, DONE і так далі.

*** Є два /типи/ станів: to-do і done

*** DONE Це нотатка з /виконаним/ типом стану
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** TODO To track the percentage of DONE vs TODO items, add [%] to the note's title

*** DONE Both can be used in tandem
CLOSED: [2025-03-13 Thu 08:37]

The order doesn't matter, and the counts will be updated automatically.

** Нотатки дозволяють планувати час
SCHEDULED: <2015-02-20 Fri 15:15>

*** Час може повторюватися
SCHEDULED: <2015-02-16 Mon .+2d>

** Ви також можете встановити час завершення
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

- <2015-02-20 Fri>
- <2015-02-21 Sat>

** Підтримуються нагадування для нотаток із запланованим часом і кінцевим терміном

За замовчуванням вони вимкнені і їх потрібно увімкнути в Налаштуваннях.

** [#A] Нотатки можуть мати пріоритет

Ви можете змінити кількість пріоритетів у Налаштуваннях. Також Ви можете змінити стандартний пріоритет, який пропонується для нотаток, де його не встановлено.

** Нотатка може мати посилання

Подзвонити за номером (tel:555-0199), надіслати SMS (sms:555-0199), написати електронного листа (mailto:support@orgzlyrevived.com) або відвідати вебсторінку ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

Також Ви можете посилатися на іншу нотатку або записник.

Детальніше дивіться [[https://www.orgzlyrevived.com/docs#links]].

** Підтримуються основні типографічні виділення

Ви можете робити слова *грубими*, /похилими/, _підкресленими_, =без форматування=, ~кодом~ і +закресленими+.

** Доступний список із вимикачами

- [X] Завдання 1
- [ ] Завдання 2
- [ ] Завдання 3

Натисніть на вимикач, щоб змінити стан. Натисніть кнопку нового рядка *⤶* в кінці рядка, щоб додати новий елемент.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Завдання 1
- [ ] Завдання 2
- [X] Завдання 3

* Пошук
** Підтримуються різні оператори пошуку

Ви можете шукати нотатки за станом, мітками, запланованим або кінцевим часом тощо.

Детальніше дивіться [[https://www.orgzlyrevived.com/docs#search]].

** Пошукові запити можна зберігати для швидкого доступу

Спробуйте приклади пошуку з меню переходів і зверніть увагу на запити, які вони використовують.

Ви можете створити свої власні пошукові запити натиснувши на «Пошукові запити» в меню переходів.

* Синхронізація

** Записники можна зберігати як прості текстові файли

Файли знаходяться у форматі, який використовує [[https://orgmode.org/][Org mode]].

** Тип розташування (репозиторію)

Ви можете зберігати свої записники в теці на своєму мобільному пристрої, SD-картці чи в Dropbox.
