Добро пожаловать в Orgzly!

* Заметки
** Нажатие для открытия заметки
** Долгое нажатие для выбора заметки

Можно выбрать несколько заметок.

** Смахивание вправо для вызова быстрого меню

Смахивание влево для вызова дополнительного меню.

** Чтобы свернуть заметку с вложенным содержимым, нажмите на значок рядом с ней

Долгое нажатие на значок разворачивает всё поддерево.

*** У заметок может быть сколько угодно уровней вложенности
**** Используйте эту возможность, чтобы лучше организовать свои заметки

** Заметкам можно добавить теги :тег1:тег2:
*** Вложенные заметки наследуют теги :тег3:

При поиске заметки с тегом «tag1» с помощью запроса «t.tag1», эта заметка будет включена в результаты поиска.

*** Заметка с тегом =ARCHIVE= выделяется серым цветом :ARCHIVE:

** TODO Заметки могут иметь состояние

Вы можете настроить любое количество состояний и использовать их: TODO, NEXT, DONE и т.

*** Существует два /типа/ состояний: запланированные (todo) и выполненные (done)

*** DONE Это заметка с /выполненным/ типом состояния
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** Время заметки может быть повторяемым
SCHEDULED: <2015-02-16 Mon .+2d>

** Вы также можете установить крайний срок для заметки
DEADLINE: <2015-02-20 Fri>

д.

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

*** Times can have a repeater
SCHEDULED: <2015-02-16 Mon .+2d>

Отметьте заметку как выполненную чтобы сдвинуть повторитель.

** [#A] Заметки могут иметь приоритет

Вы можете изменить количество приоритетов в «Настройках». Вы также можете изменить приоритет по умолчанию - подразумеваемый приоритет для заметок без установленного приоритета.

- <2015-02-20 Fri>
- <2015-02-21 Sat>

** Reminders for notes with scheduled, deadline, or event times are supported

Mark the note as done to shift the repeater.

** [#A] Note can have a priority

You can change the number of priorities in Settings. You can also change default priority - assumed priority for notes without one set.

** Note can include links

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

* Поиск
** Поддерживаются разнообразные критерии поиска

Вы можете искать заметки по состоянию, тегам, назначенному или крайнему сроку и т.

** Поисковые запросы можно сохранять для повторного использования

Попробуйте примеры сохранённых поисков в меню навигации и ознакомьтесь с используемыми в них запросами.

Вы можете сохранять ваши собственные поисковые запросы нажатием на «Поисковые запросы» в меню навигации.

** Блокноты можно сохранять в виде простых текстовых файлов

* Search
** There are many search operators supported

Репозиторий - это место в которым можно синхронизировать ваши блокноты. Вы можете хранить ваши блокноты в папке на вашем мобильном устройстве, SD-карте или в Dropbox.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
