Добро пожаловать в Orgzly!

* Заметки
** Нажатие для открытия заметки
** Долгое нажатие для выбора заметки

Можно выбрать несколько заметок.

** Смахивание вправо для вызова быстрого меню

Смахивание влево для вызова дополнительного меню.

** Чтобы свернуть заметку с вложенным содержимым, нажмите на значок рядом с ней

Долгое нажатие на значок разворачивает всё поддерево.

*** У заметок может быть сколько угодно уровней вложенности
**** Используйте эту возможность, чтобы лучше организовать свои заметки

** Заметкам можно добавить теги :тег1:тег2:
*** Вложенные заметки наследуют теги :тег3:

При поиске заметки с тегом «tag1» с помощью запроса «t.tag1», эта заметка будет включена в результаты поиска.

*** Заметка с тегом =ARCHIVE= выделяется серым цветом :ARCHIVE:

** TODO Заметки могут иметь состояние

Вы можете настроить любое количество состояний и использовать их: TODO, NEXT, DONE и т.

*** Существует два /типа/ состояний: запланированные (todo) и выполненные (done)

*** DONE Это заметка с /выполненным/ типом состояния
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** TODO To track the percentage of DONE vs TODO items, add [%] to the note's title

*** DONE Both can be used in tandem
CLOSED: [2025-03-13 Thu 08:37]

The order doesn't matter, and the counts will be updated automatically.

** Заметки могут иметь назначенное время
SCHEDULED: <2015-02-20 Fri 15:15>

*** Время заметки может быть повторяемым
SCHEDULED: <2015-02-16 Mon .+2d>

** Вы также можете установить крайний срок для заметки
DEADLINE: <2015-02-20 Fri>

** Время события может быть использованое везде внутри заметки

Вы можете иметь несколько дат событий:

- <2015-02-20 Fri>
- <2015-02-21 Sat>

** Поддерживаются напоминания для заметок с назначенным временем или крайним сроком

Отметьте заметку как выполненную чтобы сдвинуть повторитель.

** [#A] Заметки могут иметь приоритет

Вы можете изменить количество приоритетов в «Настройках». Вы также можете изменить приоритет по умолчанию - подразумеваемый приоритет для заметок без установленного приоритета.

** Заметка может содержать ссылки

Позвонить по телефону (tel:555-0199), отправить SMS (sms:555-0199), отправить электронную почту (mailto:support@orgzlyrevived.com) или посетить веб-страницу ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

Вы так же можете сослаться на другую заметку или блокнот.

Для дополнительной информации смотрите [[https://www.orgzlyrevived.com/docs#links]]

** Поддерживаются базовые средства выразительности типографики

Вы можете сделать текст *жирным*, /курсивным/, _подчёркнутым_, =выделенным=, ~моноширинным~ и +зачёркнутым+.

** Доступен список с флажками

- [X] Задача 1
- [ ] Задача 2
- [ ] Задача 3

Нажмите флажок, чтобы изменить его. Нажмите кнопку новой строки в конце линии, чтобы создать новый элемент.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Задача 1
- [ ] Задача 2
- [X] Задача 3

* Поиск
** Поддерживаются разнообразные критерии поиска

Вы можете искать заметки по состоянию, тегам, назначенному или крайнему сроку и т.

Посетите [[https://www.orgzlyrevived.com/docs#search]] чтобы узнать больше.

** Поисковые запросы можно сохранять для повторного использования

Попробуйте примеры сохранённых поисков в меню навигации и ознакомьтесь с используемыми в них запросами.

Вы можете сохранять ваши собственные поисковые запросы нажатием на «Поисковые запросы» в меню навигации.

* Синхронизация

** Блокноты можно сохранять в виде простых текстовых файлов

Файлы находятся в формате, используемом в [[https://orgmode.org/][Org mode]].

** Тип расположения (хранилища)

Репозиторий - это место в которым можно синхронизировать ваши блокноты. Вы можете хранить ваши блокноты в папке на вашем мобильном устройстве, SD-карте или в Dropbox.
