歡迎使用 Orgzly!

* 筆記
** 點選以打開筆記
** 點選並長按住筆記以選中它

您可以選擇多個筆記。

** 向右滑動筆記打開快速功能表

向左滑動以打開其他功能表

** 通過按一下旁邊的圖示來折疊包含子項目的筆記

長按圖示展開子樹集

您可以擁有無限的筆記階層數
用這個來更好的整理你的筆記

** 筆記可以有標籤如： :標籤1:標籤2:
子項目會繼承母項目的標記：:標籤3:

如果使用“t.tag1”收尋，若筆記有“tag1”的標籤，則此筆記將包含在收尋結果中。

*** 將設有= ARCHIVE = 歸檔標籤的筆記變灰 :ARCHIVE:

** TODO 筆記可以有一個狀態

您可以配置任意數量的狀態來使用: TODO、NEXT、DONE，等。

有兩種狀態類型: "待辦"與"完成"

*** DONE 是筆記“完成”類型的狀態
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** 時間可以重複
SCHEDULED: <2015-02-16 Mon .+2d>

** 還可以設置截止時間
DEADLINE: <2018-02-20 Sat>

** 支援行事曆和截止時間的提醒

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

您可以在 "設置" 中更改優先順序的數量。 您還可以更改預設優先順序，假使沒有筆記的優先順序。

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** 筆記支持基本的標記重點

你可以用兩個符號包圍字串改變文字形態如：*粗體*, /斜體/, _底線_, =代碼=, ~逐字的~, +刪除線+。

** 核取方塊清單可用

** [#A] Note can have a priority

- [X] 任務1
-[ ] 任務2
-[ ] 任務3

按一下核取方塊以切換它。 按下行末的new-line新建行，創建新項目

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
