Sveiki atvykę į Orgzly!

* Įrašai
** Spustelėkite ant įrašo, kad atidarytumėte
** Spustelėkite ir laikykite, kad įrašą pasirinktumėte

Galite pasirinkti kelis įrašus.

Braukite įrašą dešinėn, kad atidarytumėte jo iškylantį meniu

Braukite įrašą kairėn, kad atidarytumėte kitą meniu.

** Suskleiskite įrašą su poįrašiais spustelėdami šalia esančią ikoną

Ilgai spustelėkite ikoną, kad išskleistumėte visą pomedį.

*** Nėra ribos lygių kiekiui
**** Naudokite tai įrašų organizavimui

** Įrašas gali turėti žymes :tag1:tag2:
*** Poįrašis paveldi žymes :tag3:

Jei ieškote įrašų pažymėtų „tag1“ naudodami „t.tag1“ užklausa, šis įrašas bus įtrauktas paieškos rezultatuose.

*** Įrašas, kuris turi =ARCHIVE= žymę, yra papilkintas :ARCHIVE:

** TODO Įrašas gali turėti būseną

Galite sukonfiguruoti įvairias būsenas: TODO, NEXT, DONE ir t. t.

*** Yra du būsenų /tipai/: to-do (atlikti) ir done (atlikta)

*** DONE Čia yra įrašas su /done/ būsenos tipu
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** Laikai gali būti kartojami
SCHEDULED: <2015-02-16 Mon .+2d>

** Taip pat galite nustatyti terminą
DEADLINE: <2015-02-20 Fri>

** Įvykių laikai gali būti naudojami bet kur įrašo turinyje

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

*** Times can have a repeater
SCHEDULED: <2015-02-16 Mon .+2d>

Pažymėkite įrašą kaip atliktą, kad pasislinktų kartojimas.

** [#A] Įrašas gali turėti svarbą

Galite pakeisti svarbos pasirinkimų kiekį nustatymuose. Taip pat galite pakeisti numatytąją svarbą – įgaunama svarba nenustačius.

- <2015-02-20 Fri>
- <2015-02-21 Sat>

** Reminders for notes with scheduled, deadline, or event times are supported

Mark the note as done to shift the repeater.

** [#A] Note can have a priority

You can change the number of priorities in Settings. You can also change default priority - assumed priority for notes without one set.

** Note can include links

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

* Paieška
** Yra daug palaikomų paieškos operatorių

Galite ieškoti įrašų pagal būseną, žymę, suplanavimą, terminą, įvykio laiką ir t. t.

** Paieškos užklausos gali būti išsaugotos greitai prieigai

Pabandykite pavyzdines paieškas iš navigacijos skyriaus ir atsižvelkite į naudojamas užklausas.

Galite sukurti savo išsaugotas paieškas spustelėdami „Paieškos“ navigacijos skyriuje.

** Užrašinės gali būti išsaugotos kaip grynojo teksto failai

* Search
** There are many search operators supported

Saugykla yra vieta, su kuria galite sinchronizuoti savo užrašines. Saugykla gali būti katalogas jūsų mobiliajame įrenginyje, SD kortelėje ar Dropbox.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
