欢迎使用Orgzly！

* 笔记
** 单击打开笔记
** 长按选择笔记

可选择多条笔记。设置中可切换单击与长按的功能。

** 右划笔记打开快捷菜单

左划笔记打开另一个菜单。

** 点击笔记旁的图标收起笔记的子笔记

长按图标展开整个子树。

*** 没有层数限制
**** 以便更好地组织笔记

** 笔记可带有标签 :tag1:tag2:
*** 子笔记会继承父笔记的标签 :tag3:

如果您使用“t.tag1”查询符搜索带有“tag1”标签的笔记，此笔记将被列入搜索结果。

*** 带有=ARCHIVE=标签集的笔记以灰色显示 :ARCHIVE:

** TODO 笔记可具有一种状态

可在设置中配置任意数量的状态：TODO、NEXT、DONE，等等。

*** 有两种/类型/的状态：待办和完成

*** DONE 这是一条带/完成/类型状态的笔记
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** 可以为时间设定一个重复器
SCHEDULED: <2015-02-16 Mon .+2d>

** 还可以设定一个截止时间
DEADLINE: <2015-02-20 Fri>

** 支持通知提醒计划时间和截至时间

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

可在设置中更改优先级数量。 也可以更改默认优先级 - 假如还没有为笔记设定优先级。

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** 支持基本的排版强调

您可以使文字 *粗体* ， /斜体/ ， _下划线_ ， =逐字= ， ~代码~ 和 +删除线+ 。

** 支持复选框列表

** [#A] Note can have a priority

- [X] 任务 1
- [ ] 任务 2
- [ ] 任务 3

点击复选框切换状态。 点按行尾的新建行按钮以创建新条目。

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
