欢迎使用Orgzly！

* 笔记
** 单击打开笔记
** 长按选择笔记

可选择多条笔记。设置中可切换单击与长按的功能。

** 右划笔记打开快捷菜单

左划笔记打开另一个菜单。

** 点击笔记旁的图标收起笔记的子笔记

长按图标展开整个子树。

*** 没有层数限制
**** 以便更好地组织笔记

** 笔记可带有标签 :tag1:tag2:
*** 子笔记会继承父笔记的标签 :tag3:

如果您使用“t.tag1”查询符搜索带有“tag1”标签的笔记，此笔记将被列入搜索结果。

*** 带有=ARCHIVE=标签集的笔记以灰色显示 :ARCHIVE:

** TODO 笔记可具有一种状态

可在设置中配置任意数量的状态：TODO、NEXT、DONE，等等。

*** 有两种/类型/的状态：待办和完成

*** DONE 这是一条带/完成/类型状态的笔记
CLOSED: [2018-01-24 Wed 17:00]

** 父笔记可以跟踪子笔记的状态 [1/3] [33%]

*** TODO 若要跟踪 TODO 事项与 DONE 事项的比例，请在笔记标题中添加 [/]

*** TODO 若要跟踪 DONE 事项与 TODO 事项的百分比，请在笔记标题中添加 [%]

*** DONE 两者可以同时使用
CLOSED: [2025-03-13 Thu 08:37]

顺序无关紧要，数量会自动更新。

** 可以为笔记设置一个计划时间
SCHEDULED: <2015-02-20 Fri 15:15>

*** 可以为时间设定一个重复器
SCHEDULED: <2015-02-16 Mon .+2d>

** 还可以设定一个截止时间
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

- <2015-02-20 Fri>
- <2015-02-21 Sat>

** 支持通知提醒计划时间和截至时间

此功能默认关闭，需要在设置中启用。

** [#A] 笔记可以具有优先级

可在设置中更改优先级数量。 也可以更改默认优先级 - 假如还没有为笔记设定优先级。

** 笔记可以包含链接

拨打电话 (tel:555-0199)， 发送短信 (sms:555-0199)， 写邮件 (mailto:support@orgzlyrevived.com) 或访问网页 ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]])。

也可以在应用程序内链接到其他笔记或笔记本。

访问 [[https://www.orgzlyrevived.com/docs#links]] 了解更多信息。

** 支持基本的排版强调

您可以使文字 *粗体* ， /斜体/ ， _下划线_ ， =逐字= ， ~代码~ 和 +删除线+ 。

** 支持复选框列表

- [X] 任务 1
- [ ] 任务 2
- [ ] 任务 3

点击复选框切换状态。 点按行尾的新建行按钮以创建新条目。

** 笔记的标题也可以跟踪复选框列表的状态 [66%] [2/3]

- [X] 任务 1
- [ ] 任务 2
- [X] 任务 3

* 搜索
** 支持多种搜索运算符

可通过状态，标签，计划时间或截止时间等搜索笔记

访问 [[https://www.orgzlyrevived.com/docs#search]] 了解更多。

** 可保存搜索查询串以便快速访问

从导航抽屉中尝试示例搜索并注意它们所使用的查询串。

可通过点击导航抽屉中的“搜索”创建和保存自定义搜索。

* 同步

** 笔记本可保存为纯文本文件

文件使用 [[https://orgmode.org/][Org mode]] 的格式。

** 位置(存储库)类型

可将笔记本与设备存储，SD 卡或 Dropbox 上的一个目录同步。
