Orgzly에 오신 것을 환영합니다!

* 메모
** 메모 내용을 보시려면 클릭하세요.
** 메모를 선택하시려면 길게 클릭하세요.

여러개의 메모를 선택할 수 있습니다.

** 메모의 오른쪽을 선택하면 퀵메뉴를 열 수 있습니다.

왼쪽을 선택하면 다른 메뉴가 열립니다.

** 옆의 아이콘을 눌러서 하위 메모를 숨길 수 있습니다.

Long-click the icon to unfold entire subtree.

*** 제한없이 하위 메모를 만들 수 있습니다.
**** 메모를 잘 정리하려면 이 항목을 사용하세요.

** 메모에 태그를 달 수 있습니다 :tag1:tag2:
*** 하위 메모는 상위 메모의 태그를 물려받습니다. :tag3:

If you search for notes with tag “tag1” using “t.tag1” query, this note will be included in search results.

*** A note that has the =ARCHIVE= tag set is grayed out :ARCHIVE:

** TODO 메모에 처리 상태를 설정할 수 있습니다.

처리상태: TODO, NEXT, DONE, etc.

*** 두 /종류/의 상태 : 할 일과 완료

*** DONE 메모의 처리가 /완료/되었습니다.
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** 일정을 반복할 수 있습니다.
SCHEDULED: <2015-02-16 Mon .+2d>

** 마감일을 설정할 수 있습니다.
DEADLINE: <2015-02-20 Fri>

** 예정일과 마감일에 대해 알림 기능을 제공합니다.

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

우선 순위를 변경할 수 있습니다. 우선 순위를 설정하지 않은 메모에 대한 기본 우선 순위를 변경할 수 있습니다.

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** 기본적인 글자 강조 기능을 사용할 수 있습니다.

*굵게*, /기울기/, _밑줄_, =인용=, ~수식~, +취소+ 단어를 표현할 수 있습니다.

** 확인란 목록을 사용할 수 있습니다.

** [#A] Note can have a priority

- [X] 작업 1
- [ ] 작업 2
- [ ] 작업 3

확인 란을 클릭하면 상태가 변경됩니다. 줄 끝에 있는 새 줄 단추를 눌러 새 항목을 만드세요.

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
