Сардэчна вітаем у Orgzly!

* Нататкі
** Націсьніце, каб адкрыць нататку
** Націсьніце ды ўтрымлівайце, каб выбраць нататку

Ільга выбраць некалькі нататак.

** Тарганіце нататку ўправа, каб адкрыць хуткае мэню

Тарганіце ўлева, каб адкрыць дадатковае мэню.

** Каб згарнуць нататку разам з даччынаю, націсьніце на значок побач зь ёй

Працяглае націсканьне на значок цалкам разгортвае даччынае дрэва.

*** Неабмежаваная колькасьць узроўняў нататак
**** Выкарыстоўвайце гэтае, каб лепей арганізаваць свае нататкі

** Нататкі могуць мець меткі :метка1:метка2:
*** Даччыная нататка ўнасьледуе меткі :метка3:

Пры пошуку нататкі зь меткаю «метка1» праз запыт «t.метка1», то гэтая нататка будзе ўключаная ў выніках пошуку.

*** Нататка зь меткаю =ARCHIVE= вылучаецца шэрым :ARCHIVE:

** TODO Нататкі могуць мець стан

Вы можаце наладзіць колькі заўгодна станаў на выкарыстаньне: TODO, NEXT, DONE, ды інш.

*** Існуюць два /тыпы/ станаў: to-do ды done

*** DONE Такая нататка з /выкананым/ тыпам стану
CLOSED: [2018-01-24 Срд 17:00]

** Нататкі могуць мець заплянаваны час
SCHEDULED: <2015-02-20 Пят 15:15>

*** Час можа мець паўтаральнік
SCHEDULED: <2015-02-16 Пан .+2д>

** Вы таксама можаце задаць тэрмін
DEADLINE: <2015-02-20 Пят>

** Часы падзеі ільга адзначаць дзе заўгодна ў зьмесьце нататкі

Ільга мець некалькі часоў падзеі:

- <2015-02-20 Пят>
- <2015-02-21 Суб>

** Падтрымліваюцца нагадваньні ў нататак з заплянаваным часам ды тэрмінам

Пазначце нататку як выкананую, каб зрушыць паўтаральнік.

** [#A] Нататкі могуць мець прыярытэт

Ільга зьмяніць колькасьць прыярытэтаў у наладах. Вы таксама можаце зьмяніць прадвызначаны прыярытэт - разьлічаны на нататкі, дзе ён ня вызначаны.

** Нататка можа зьмяшчаць спасылкі

Патэлефанаваць на нумар (tel:555-0199), надаслаць SMS (sms:555-0199), напісаць электронны ліст (mailto:support@orgzlyrevived.com), або наведаць вэб-старонку ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

Таксама ільга спасылацца на іншую нататку ці нататнік у праграме.

Глядзіце дадатковыя зьвесткі на [[https://www.orgzlyrevived.com/docs#links]].

** Падтрымліваюцца асноўныя друкарскія выдзяленьні

Ільга рабіць тэкст *тлустым*, /курсіўным/, _падкрэсьленым_, =вылучаным=, ~кодам~ ды +закрэсьленым+.

** Даступны сьпіс з птушкамі

- [X] Заданьне 1
- [ ] Заданьне 2
- [ ] Заданьне 3

Націсьніце на поле, каб зьмяніць стан. Націсьніце кнопку новага радка ў канцы радка, каб стварыць новы элемэнт.

* Пошук
** Падтрымліваюцца разнастайныя апэратары пошуку

Ільга шукаць нататкі па стану, метках, заплянаванаму часу ці тэрміну й г.д.

Глядзіце [[https://www.orgzlyrevived.com/docs#search]], каб даведацца больш.

** Пошукавыя запыты можна захоўваць дзеля хуткага доступу

Паспрабуйце прыклады пошуку з панэлі навігацыі й зьвярніце ўвагу на запыты, якія там выкарыстоўваюцца.

Ільга стварыць свае ўласныя пошукавыя запыты націсканьнем на «Пошукавыя запыты» ў панэлі навігацыі.

* Сынхранізацыя

** Нататнікі могуць захоўвацца як простыя тэкставыя файлы

Файлы захоўваюцца ў фармаце паводле [[https://orgmode.org/][Org mode]].

** Тып разьмяшчэньня (рэпазітара)

Рэпазітар - гэта месца, зь якім вы можаце сынхранізаваць свае нататнікі. Вы можаце трымаць нататнікі ў каталозе на сваёй мабільнай прыладзе, SD-картцы ці ў Dropbox.
