Сардэчна вітаем у Orgzly!

* Нататкі
** Націсьніце, каб адкрыць нататку
** Націсьніце ды ўтрымлівайце, каб выбраць нататку

Ільга выбраць некалькі нататак.

** Тарганіце нататку ўправа, каб адкрыць хуткае мэню

Тарганіце ўлева, каб адкрыць дадатковае мэню.

** Каб згарнуць нататку разам з даччынаю, націсьніце на значок побач зь ёй

Працяглае націсканьне на значок цалкам разгортвае даччынае дрэва.

*** Неабмежаваная колькасьць узроўняў нататак
**** Выкарыстоўвайце гэтае, каб лепей арганізаваць свае нататкі

** Нататкі могуць мець меткі :метка1:метка2:
*** Даччыная нататка ўнасьледуе меткі :метка3:

Пры пошуку нататкі зь меткаю «метка1» праз запыт «t.метка1», то гэтая нататка будзе ўключаная ў выніках пошуку.

*** Нататка зь меткаю =ARCHIVE= вылучаецца шэрым :ARCHIVE:

** TODO Нататкі могуць мець стан

Вы можаце наладзіць колькі заўгодна станаў на выкарыстаньне: TODO, NEXT, DONE, ды інш.

*** Існуюць два /тыпы/ станаў: to-do ды done

*** DONE Такая нататка з /выкананым/ тыпам стану
CLOSED: [2018-01-24 Срд 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** Час можа мець паўтаральнік
SCHEDULED: <2015-02-16 Пан .+2д>

** Вы таксама можаце задаць тэрмін
DEADLINE: <2015-02-20 Пят>

** Часы падзеі ільга адзначаць дзе заўгодна ў зьмесьце нататкі

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

*** Times can have a repeater
SCHEDULED: <2015-02-16 Mon .+2d>

Пазначце нататку як выкананую, каб зрушыць паўтаральнік.

** [#A] Нататкі могуць мець прыярытэт

Ільга зьмяніць колькасьць прыярытэтаў у наладах. Вы таксама можаце зьмяніць прадвызначаны прыярытэт - разьлічаны на нататкі, дзе ён ня вызначаны.

- <2015-02-20 Fri>
- <2015-02-21 Sat>

** Reminders for notes with scheduled, deadline, or event times are supported

Mark the note as done to shift the repeater.

** [#A] Note can have a priority

You can change the number of priorities in Settings. You can also change default priority - assumed priority for notes without one set.

** Note can include links

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

* Пошук
** Падтрымліваюцца разнастайныя апэратары пошуку

Ільга шукаць нататкі па стану, метках, заплянаванаму часу ці тэрміну й г.д.

** Пошукавыя запыты можна захоўваць дзеля хуткага доступу

Паспрабуйце прыклады пошуку з панэлі навігацыі й зьвярніце ўвагу на запыты, якія там выкарыстоўваюцца.

Ільга стварыць свае ўласныя пошукавыя запыты націсканьнем на «Пошукавыя запыты» ў панэлі навігацыі.

** Нататнікі могуць захоўвацца як простыя тэкставыя файлы

* Search
** There are many search operators supported

Рэпазітар - гэта месца, зь якім вы можаце сынхранізаваць свае нататнікі. Вы можаце трымаць нататнікі ў каталозе на сваёй мабільнай прыладзе, SD-картцы ці ў Dropbox.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
