Welkom bij Orgzly!

* Notities
** Klik op de notitie om haar te openen
** Klik en houd ingedrukt om de notitie te selecteren

Je kunt meerdere notities selecteren.

** Veeg de notitie naar rechts om haar snelmenu te openen

Veeg het naar links om een ander menu te openen.

** Vouw een notitie met subnotities door op het icoon ernaast te klikken

Lang klikken op het pictogram om volledig te ontvouwen.

*** Er is geen limiet op het aantal niveaus dat je kunt hebben
**** Gebruik dit om je notities beter te organiseren

** Een notitie kan labels hebben :label1:label2:
*** Subnotities erven deze labels :label3:

Als u notities zoekt met tag "tag1" met "t.tag1" zoekopdracht, zal deze notitie worden opgenomen in zoekresultaten.

*** Een notitie welke de =ARCHIVE= tag gezet heeft, wordt uitgegrijst :ARCHIVE:

** TODO Een notitie kan een status hebben

Je kunt zo veel statussen configureren als je wilt: TODO, NEXT, DONE, etc.

*** Er zijn twee /types/ van statussen: to-do en done

*** DONE Dit is een notitie met een /done/ type status
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** Tijden kunnen een herhaler hebben
SCHEDULED: <2015-02-16 Mon .+2d>

** Je kunt ook een deadlinetijd instellen
DEADLINE: <2015-02-20 Fri>

** Herinneringen aan geplande en deadline tijdstippen zijn ondersteund

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

U kunt het aantal prioriteiten in Instellingen wijzigen. U kunt ook de standaard prioriteit - aangenomen prioriteit wijzigen voor notities zonder één set.

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** Typografische basisaccentuering wordt ondersteund

Je kunt worden *dikgedrukt*, /schuin/, _onderstreept_, =verbato=, ~code~ en +doorgestreept+ maken.

** Checkbox lijst is beschikbaar

** [#A] Note can have a priority

- [X] Taak 1
- [ ] Taak 2
- [ ] Taak 3

Klik op de checkbox om het aan te vinken. Druk op de nieuwe-lijnknop aan het einde van de regel om een nieuw item aan te maken.

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
