Üdv az Orgzly jegyzetelőben!

* Jegyzetek
** Koppints a bejegyzés megnyitásához
** Tartsd lenyomva a bejegyzés kijelöléséhez

Kijelölhetsz több bejegyzést is.

** Jobbra simítva megnyílik a gyorsmenü

Balra simítva egy másik menü nyílik meg.

** Ha egy bejegyzés tartalmaz aljegyzeteket is, be lehet hajtogatni azokat, ha az ikonra koppintasz mellette

Hosszú koppintás az ikonon megnyitja az egész fát.

*** Nincs korlátozva, hogy hány szinten lehet aljegyzet
**** Így könnyebb elrendezni a bejegyzéseket

** Lehet címkéket is ragasztani bejegyzésekre :címke1:címke2:
*** Az aljegyzet örökli a címkéket :címke3:

Ha a "címke1" címkéjű bejegyzéseket keresed a "t.címke1" lekérdezés használatával, akkor ez a bejegyzés benne lesz a keresési eredményben.

*** Az =ARCHIVE= -nak cimkézett jegyzet kiszürkített :ARCHIVE:

** TODO Egy bejegyzésnek állapota is lehet

Létre lehet hozni akárhány állapot jelzőt: TODO, NEXT, DONE, stb.

*** Kétféle /típusa/ lehet az állapotoknak: to-do (tennivaló) és done (kész)

*** DONE Ennek a bejegyzésnek az állapota /done/, vagyis /kész/
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** Ismétlődő időt is be lehet állítani
SCHEDULED: <2015-02-16 Mon .+2d>

** Határidőt is be lehet állítani
DEADLINE: <2015-02-20 Fri>

** Az ütemezett és a határidőkhöz emlékeztetőt is lehet beállítani

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

A prioritások számát megadhatod a Beállításokban. Az alap prioritást is át lehet állítani - bármely bejegyzésnek ez lesz a prioritása ha nincs külön beállítva.

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** Az alapvető tipográfiai kiemeléseket támogatja a program

Lehet egy szó *félkövér*, /dőlt/, _aláhúzva_, =szó szerinti=, ~kód~ és +áthúzva+.

** Jelölő négyzetet is használhatunk

** [#A] Note can have a priority

- [X] Első feladat
- [ ] Második feladat
- [ ] Harmadik feladat

Kattintás a jelölőnégyzetre átváltja azt. Új elem létrehozása a sor végén az új-sor gomb megnyomásával a is lehetséges.

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
