Orgzly'e Hoşgeldiniz!

* Notlar
** Açmak için nota tıkla
** Seçmek için nota tıklayıp basılı tut

Birden fazla not seçebilirsin.

** Hızlı menüyü açmak için notu sağa kaydır

Farklı bir menüye ulaşmak için notu sola kaydır.

** Yanındaki simgeye tıklayarak alt notlar içeren bir notu katlayabilirsin

Alt ağacın tamamını açmak için simgeye basılı tut.

*** Sahip olabileceğiniz seviyelerin sınırı yok
**** Notlarınızı daha iyi düzenlemek için bunu kullanın

** Notların etiketleri olabilir :tag1:tag2:
*** Alt not etiketleri devralır :tag3:

“t.tag1” sorgusunu kullanarak “tag1” etiketli notları ararsan bu not arama sonuçlarına dahil edilir.

*** =ARCHIVE= olarak etiketli bir not gri renkte görünür :ARCHIVE:

** TODO Notlar bir durum belirtebilir

Kullanılacak istediğiniz sayıda durumu yapılandırabilirsiniz: YAPILACAKLAR, SONRAKİ, YAPILDI vb.

*** İki tür/durum vardır: yapılacak ve yapılan

*** TAMAMLANDI Bu, /done/ türünde bir durum içeren bir nottur
CLOSED: [2024-01-10 Çrş 22:09]

** Notların yapılması için bir zaman belirlenebilir
SCHEDULED: <2024-01-10 Çrş 22:09>

Belirlenen zamanlara tekrarlayıcı eklenebilir
SCHEDULED: <2024-01-10 Çrş .+3d>

** Notlara bitiş tarihi de eklenebilir
DEADLINE: <2024-01-10 Çrş>

** Planlamalar ve bitiş tarihleri için hatırlatma desteği

Varsayılan olarak devre dışıdırlar ve Ayarlar'da etkinleştirilmeleri gerekir.

** [#A] Notların öncelikleri olabilir

Önceliklerin numarasını ayarlardan değiştirebilirsiniz. Ayrıca varsayılan önceliği değiştirebilirsiniz - tek notlar için varsayılan öncelik.

** Not bağlantılar içerebilir

Bir telefon numarası çevirin (tel:555-0199), SMS gönderin (sms:555-0199), e-posta oluşturun (mailto:support@orgzly.com) veya bir web sayfasını ziyaret edin ([[http://www.orgzly.com][Orgzly.com]]).

Ayrıca uygulama içindeki başka bir nota veya deftere bağlantı verilebilir.

Daha fazla bilgi için http://www.orgzly.com/help#links adresine bakın.

** Temel tipografik vurgu desteklenmekte

Kelimeler *kalın*, /italik/, _altı çizili_, =verbatim=, ~kod~ ve +üstü çizili+ yapılabilir.

** Onay kutusu listesi kullanılabilir

- [X] Görev 1
- [ ] Görev 2
- [ ] Görev 3

Değiştirmek için onay kutusunu tıklayın. Yeni bir öğe oluşturmak için satırın sonundaki yeni satır düğmesine tıklayın.

* Arama
** Birçok arama operatörü desteklenmektedir

Notlar durumlara, etiketlere, planlanma durumuna veya bitiş tarihlerine vb. göre aranabilir.

Daha fazla bilgi edinmek için http://www.orgzly.com/help#search adresine göz at.

** Hızlı erişim için arama sorguları kaydedilebilir

Gezinme çekmecesinden örnek aramaları dene ve kullandıkları sorguları not et.

Gezinme çekmecesindeki "Aramalar"ı tıklayarak kendi kayıtlı aramalarını oluşturabilirsin.

* Senkronizasyon

** Defterler düz metin dosyaları olarak kaydedilebilir

Dosyalar “Org mod” tarafından kullanılan formattadır.

** Konum (depo) türü

Defterleri mobil cihazındaki bir dizine, SD kartına veya Dropbox'a eşitleyebilirsin.
