Orgzly'e Hoşgeldiniz!

* Notlar
** Açmak için nota tıkla
** Seçmek için nota tıklayıp basılı tut

Birden fazla not seçebilirsin.

** Hızlı menüyü açmak için notu sağa kaydır

Farklı bir menüye ulaşmak için notu sola kaydır.

** Yanındaki simgeye tıklayarak alt notlar içeren bir notu katlayabilirsin

Alt ağacın tamamını açmak için simgeye basılı tut.

*** Sahip olabileceğiniz seviyelerin sınırı yok
**** Notlarınızı daha iyi düzenlemek için bunu kullanın

** Notların etiketleri olabilir :tag1:tag2:
*** Alt not etiketleri devralır :tag3:

“t.tag1” sorgusunu kullanarak “tag1” etiketli notları ararsan bu not arama sonuçlarına dahil edilir.

*** =ARCHIVE= olarak etiketli bir not gri renkte görünür :ARCHIVE:

** TODO Notlar bir durum belirtebilir

Kullanılacak istediğiniz sayıda durumu yapılandırabilirsiniz: YAPILACAKLAR, SONRAKİ, YAPILDI vb.

*** İki tür/durum vardır: yapılacak ve yapılan

*** TAMAMLANDI Bu, /done/ türünde bir durum içeren bir nottur
CLOSED: [2024-01-10 Çrş 22:09]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

Belirlenen zamanlara tekrarlayıcı eklenebilir
SCHEDULED: <2024-01-10 Çrş .+3d>

** Notlara bitiş tarihi de eklenebilir
DEADLINE: <2024-01-10 Çrş>

** Planlamalar ve bitiş tarihleri için hatırlatma desteği

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

Önceliklerin numarasını ayarlardan değiştirebilirsiniz. Ayrıca varsayılan önceliği değiştirebilirsiniz - tek notlar için varsayılan öncelik.

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** Temel tipografik vurgu desteklenmekte

Kelimeler *kalın*, /italik/, _altı çizili_, =verbatim=, ~kod~ ve +üstü çizili+ yapılabilir.

** Onay kutusu listesi kullanılabilir

** [#A] Note can have a priority

- [X] Görev 1
- [ ] Görev 2
- [ ] Görev 3

Değiştirmek için onay kutusunu tıklayın. Yeni bir öğe oluşturmak için satırın sonundaki yeni satır düğmesine tıklayın.

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
