Orgzly'e Hoşgeldiniz!

* Notlar
** Açmak için nota tıkla
** Seçmek için nota tıklayıp basılı tut

Birden fazla not seçebilirsin.

** Hızlı menüyü açmak için notu sağa kaydır

Farklı bir menüye ulaşmak için notu sola kaydır.

** Yanındaki simgeye tıklayarak alt notlar içeren bir notu katlayabilirsin

Alt ağacın tamamını açmak için simgeye basılı tut.

*** Sahip olabileceğiniz seviyelerin sınırı yok
**** Notlarınızı daha iyi düzenlemek için bunu kullanın

** Notların etiketleri olabilir :tag1:tag2:
*** Alt not etiketleri devralır :tag3:

“t.tag1” sorgusunu kullanarak “tag1” etiketli notları ararsan bu not arama sonuçlarına dahil edilir.

*** =ARCHIVE= olarak etiketli bir not gri renkte görünür :ARCHIVE:

** TODO Notlar bir durum belirtebilir

Kullanılacak istediğiniz sayıda durumu yapılandırabilirsiniz: YAPILACAKLAR, SONRAKİ, YAPILDI vb.

*** İki tür/durum vardır: yapılacak ve yapılan

*** TAMAMLANDI Bu, /done/ türünde bir durum içeren bir nottur
CLOSED: [2024-01-10 Çrş 22:09]

** Ana notlar alt notların durumunu takip edebilir [1/3] [33%]

*** TODO TODO ve DONE öğelerinin oranını takip etmek için notun başlığına [/] ekleyin

*** TODO Tamamlanan ve TODO öğelerinin yüzdesini takip etmek için notun başlığına [%] ekleyin

*** DONE her ikiside birlikte kullanılabilinir
CLOSED: [2025-03-13 Per 08:37]

Sıralama önemli değil, sayaçlar otomatik olarak güncellenecektir.

** Notların yapılması için bir zaman belirlenebilir
SCHEDULED: <2024-01-10 Çrş 22:09>

Belirlenen zamanlara tekrarlayıcı eklenebilir
SCHEDULED: <2024-01-10 Çrş .+3d>

** Notlara bitiş tarihi de eklenebilir
DEADLINE: <2024-01-10 Çrş>

** Etkinlik zamanları not içeriğinde herhangi bir yerde kullanılabilinir

Birden fazla etkinlik zamanı olabilir:

- <2015-02-20 Cum>
- <2015-02-21 Cmt>

** Planlamalar ve bitiş tarihleri için hatırlatma desteği

Varsayılan olarak devre dışıdırlar ve Ayarlar'da etkinleştirilmeleri gerekir.

** [#A] Notların öncelikleri olabilir

Önceliklerin numarasını ayarlardan değiştirebilirsiniz. Ayrıca varsayılan önceliği değiştirebilirsiniz - tek notlar için varsayılan öncelik.

** Not bağlantılar içerebilir

Bir telefon numarası çevirin (tel:555-0199), SMS gönderin (sms:555-0199), e-posta oluşturun (mailto:support@orgzlyrevived.com) veya bir web sayfasını ziyaret edin ([[http://www.orgzlyrevived.com][Orgzlyrevived.com]]).

Ayrıca uygulama içindeki başka bir nota veya deftere bağlantı verilebilir.

Daha fazla bilgi için [[http://www.orgzlyrevived.com/docs#links]] adresine bakın.

** Temel tipografik vurgu desteklenmekte

Kelimeler *kalın*, /italik/, _altı çizili_, =verbatim=, ~kod~ ve +üstü çizili+ yapılabilir.

** Onay kutusu listesi kullanılabilir

- [X] Görev 1
- [ ] Görev 2
- [ ] Görev 3

Değiştirmek için onay kutusunu tıklayın. Yeni bir öğe oluşturmak için satırın sonundaki yeni satır düğmesine tıklayın.

** Bir notun başlığı, onay kutusu listesinin durumunu da takip edebilir  [66%] [2/3]

- [X] Görev 1
- [ ] Görev 2
- [X] Görev 3

* Arama
** Birçok arama operatörü desteklenmektedir

Notlar durumlara, etiketlere, planlanma durumuna veya bitiş tarihlerine vb. göre aranabilir.

Daha fazla bilgi edinmek için [[http://www.orgzlyrevived.com/docs#search]] adresine göz at.

** Hızlı erişim için arama sorguları kaydedilebilir

Gezinme çekmecesinden örnek aramaları dene ve kullandıkları sorguları not et.

Gezinme çekmecesindeki "Aramalar"ı tıklayarak kendi kayıtlı aramalarını oluşturabilirsin.

* Senkronizasyon

** Defterler düz metin dosyaları olarak kaydedilebilir

Dosyalar [[https://orgmode.org/][Org mod]] tarafından kullanılan formattadır.

** Konum (depo) türü

Defterleri mobil cihazındaki bir dizine, SD kartına veya Dropbox'a eşitleyebilirsin.
