Benvenuto su Orgzly!

* Note
** Clicca sulla nota per aprirla
** Tieni premuta la nota per selezionarla

Puoi selezionare più note.

** Tieni premuto e muovi velocemente a destra per aprire il suo menu rapido

Trascina verso sinistra per aprire un menu diverso.

** Apri una nota che contiene sotto-note premendo sull'icona vicina ad essa

Fare clic sull'icona per dispiegare l'intero sotto-albero.

** Non ci sono limiti al numero di livelli che puoi avere
**** Usalo per meglio organizzare le tue note

*** Ora puoi avere anche le etichette :tag1:tag2:
*** La sotto-nota eredita l'etichetta :tag3:

Se si cerca note con tag “tag1” utilizzando la query “t.tag1”, questa nota sarà inclusa nei risultati di ricerca.

*** A note that has the =ARCHIVE= tag set is grayed out :ARCHIVE:

** TODO La nota può avere uno stato

È possibile configurare qualsiasi numero di stati da usare: TODO, NEXT, DONE, ecc.

*** Ci sono due /tipi/ di stati: todo e done

*** DONE Questa è una nota con il tipo di stato /Done/
CLOSED: [2018-01-24 Mer 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** Gli orari possono avere una ripetizione
SCHEDULED: <2015-02-16 Lun .+2d>

** Puoi anche stabilire una scadenza
DEADLINE: <2015-02-20 Ven>

** Sono supportati i promemoria per i task pianificati e per le scadenze

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

È possibile modificare il numero di priorità nelle impostazioni. Puoi anche cambiare la priorità predefinita - la proprietà impostata per le note in cui non viene specificata.

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** Sono supportati i livelli di formattazione base

Puoi usare parole in *grassetto*, /corsivo/, _sottolineato_, =scandito=, ~tipo codice~ e +barrato+.

** È disponibile una lista di checkbox

** [#A] Note can have a priority

- [X] Attività 1
- [ ] Attività 2
- [ ] Attività 3

Fare clic sulla casella per cambiare lo stato. Premere il pulsante nuova riga alla fine della linea per creare un nuovo elemento.

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
