Vítejte v Orgzly!

* Poznámky
** Klikněte na poznámku, pro její otevření
** Klikněte a držte na poznámce, pro vybrání

Můžete vybrat více poznámek.

** Přetáhněte poznámku doprava pro rychlé menu

Přetáhněte ji doleva pro jiné menu.

** Složte poznámku obsahující pod-poznámky kliknutím na ikonu odrážky

Kliknutí a podržení ikony rozvine celý úsek.

*** Počet pod-úrovní je neomezený
**** Využijte toho pro lepší organizaci vašich poznámek

** Poznámky mohou mít štítky :štítek1:štítek2:
*** Pod-poznámky štítky dědí :štítek3:

Při hledání poznámek se štítkem "štítek1" a použijete "t.štítek1", bude tato poznámka zahrnuta do výsledků hledání.

*** Poznámka s nastaveným =ARCHIVE= štítkem je zašedlá :ARCHIVE:

** TODO Poznámka může mít stav

Lze nastavit množství stavů: TODO, NEXT, DONE, atd.

*** Existují dva /typy/ stavů: k udělání a hotovo

*** DONE je dokončená poznámka, se stavem /done/
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** Časy mohou obsahovat opakovač
SCHEDULED: <2015-02-16 Mon .+2d>

** Můžete také nastavit termín
DEADLINE: <2015-02-20 Fri>

** Upozornění pro časy plánované a časy po termínu jsou podporovány

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

Priority můžete nastavit v Nastavení. Můžete také nastavit výchozí prioritu - předpokládanou prioritu pro poznámky bez nastavené priority.

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** Základní typografická zvýraznění jsou podporována

Slova lze označit jako *tučná*, /kurzíva/, _podtržená_, =doslovná=, ~kód~ a +přeškrtnutá+.

** Zaškrtávací políčka jsou k dispozici

** [#A] Note can have a priority

- [X] Úkol 1
- [ ] Úkol 2
- [ ] Úkol 3

Klikněte na zaškrtávací políčko pro odškrtnutí. Klikněte na ikonu nového-řádku na konci řádku pro vytvoření nové položky.

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
