Selamat datang di Orgzly!

* Catatan
** Click on the note to open it
** Click and hold the note to select it

Anda dapat membuat beberapa catatan.

** Fling note right to open its quick-menu

Fling it left to open a different menu.

** Lipat catatan yang berisi sub-catatan dengan mengklik ikon di sebelahnya

Long-click the icon to unfold entire subtree.

*** Tidak ada batas jumlah level yang bisa anda miliki
**** Gunakan ini untuk mengatur catatan anda dengan lebih baik

** Catatan harus ada tag :tag1:tag2:
*** Sub-catatan mewarisi tag :tag3:

If you search for notes with tag “tag1” using “t.tag1” query, this note will be included in search results.

*** A note that has the =ARCHIVE= tag set is grayed out :ARCHIVE:

** Catatan TODO harus memiliki status

Anda dapat mengkonfigurasi sejumlah bagian negara untuk menggunakan: TODO, NEXT, DONE, dll.

*** Ada dua /tipe/ status: to-do dan selesai

*** DONE Ini adalah catatan dengan tipe status /selesai/
CLOSED: [2018-01-24 Wed 17:00]

** Parent notes can track state of child notes [1/3] [33%]

*** TODO To track the ratio of TODO vs DONE items, add [/] to the note's title

*** Waktu bisa memiliki pengulang
SCHEDULED: <2015-02-16 Mon .+2d>

** Anda juga bisa menetapkan tanggal waktu
DEADLINE: <2015-02-20 Fri>

** Pengingat jadwal dan deadline juga didukung

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Event times can be used anywhere in the note's content

You can have multiple event times:

** Dasar tekanan typografi di dukung

Kamu bisa membuat kata *tebal*, /miring/, _bergaris bawah_, =verbatim=, ~kode~ dan +dicoret+.

** Checkbox list is available

** [#A] Note can have a priority

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press new-line button at the end of the line to create a new item.

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzlyrevived.com) or visit a webpage ([[https://www.orgzlyrevived.com][Orgzlyrevived.com]]).

You can also link to another note or notebook within the app.

See [[https://www.orgzlyrevived.com/docs#links]] for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press the new-line button at the end of the line to create a new item.

** A note's title can also track checkbox list states [66%] [2/3]

- [X] Task 1
- [ ] Task 2
- [X] Task 3

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled, deadline or event times, etc.

See [[https://www.orgzlyrevived.com/docs#search]] to learn more.

** Search queries can be saved for quick access

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing

** Notebooks can be saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

** Location (repository) type

A repository is a location you can sync your notebooks with. A repository can be a directory on your mobile device, SD card, or Dropbox.
